name: Build Cape Launch ICS
on:
  schedule:
    - cron:  '0 */6 * * *'   # every 6 h (UTC on GitHub runners)
  workflow_dispatch:         # manual button
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: pip install icalendar pytz requests
      - name: Generate ICS
        run: python generate_ics.py
      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions@users.noreply.github.com"
          git add cape_launches.ics
          if ! git diff --cached --quiet; then
            git commit -m "auto: refresh launch feed"
            git push
          fi
